brew "neovim"
brew "python"
brew "kubectl"
brew "tmux"
brew "webp"
brew "node"
brew "hub"
brew "htop"
brew "jq"
brew "just"
brew "cfssl" # For standalone GCP Kubeconfig
brew "cmake"
brew "llvm"
brew "wget"
brew "starship"
brew "fish"
brew "awscli"
brew "bat"

cask "visual-studio-code"
cask "iterm2"
cask "google-cloud-sdk"
