#!/bin/bash -ex
# inspired from https://gist.github.com/2913223

##########################################
# Only needed if starting from fresh $HOME
##########################################
if [[ ! -e $HOME/.homesick ]]; then
  # Prerequisites to run this script:
  # SSH key that Github understands so we can checkout our dotfiles repo
  
  # Install Homeshick
  git clone git://github.com/andsens/homeshick.git $HOME/.homesick/repos/homeshick
  printf '\nsource $HOME/.homesick/repos/homeshick/homeshick.sh\n' >> $HOME/.bashrc
  source $HOME/.bashrc
  
  homeshick clone git@github.com:binarybana/dotfiles.git
fi
##########################################
# endif
##########################################

sudo dnf install $(cat $HOME/.homesick/repos/dotfiles/pkg-list.yum)
sudo pip install $(cat $HOME/.homesick/repos/dotfiles/pip-list)
# Open vim: :PluginInstall
#echo "openout_any = a" >> /usr/share/texlive/texmf-dist/web2c/texmf.cnf

chsh --shell /bin/zsh

su -c 'yum localinstall -y https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm'

su -c 'yum localinstall --nogpgcheck -y http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm'

# Font rendering in fedora from:
# https://www.happyassassin.net/2014/01/17/fonts-and-font-sizes-in-fedora-on-the-internet-hold-onto-your-hats/

# For Samsung Ultrabook with Logitech MK700: 
# xinput set-prop 'Logitech M705' 'Evdev Scrolling Distance' 4, 4, 4

