#!/bin/bash -ex
# inspired from https://gist.github.com/2913223

##########################################
# Only needed if starting from fresh $HOME
##########################################
if [[ ! -e $HOME/.homesick ]]; then
  # Prerequisites to run this script:
  # SSH key that Github understands so we can checkout our dotfiles repo
  
  # Install Homeshick
  git clone git://github.com/andsens/homeshick.git $HOME/.homesick/repos/homeshick
  printf '\nsource $HOME/.homesick/repos/homeshick/homeshick.sh\n' >> $HOME/.bashrc
  source $HOME/.bashrc
  
  homeshick clone git@github.com:binarybana/dotfiles.git
fi
##########################################
# endif
##########################################

sudo dnf install $(cat $HOME/.homesick/repos/dotfiles/pkg-list.dnf)
sudo pip install $(cat $HOME/.homesick/repos/dotfiles/pip-list)
# Open vim: :PluginInstall
#echo "openout_any = a" >> /usr/share/texlive/texmf-dist/web2c/texmf.cnf

chsh --shell /bin/zsh

sudo dnf install -y https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm

sudo dnf install --nogpgcheck -y http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# Font rendering in fedora from:
# https://www.happyassassin.net/2014/01/17/fonts-and-font-sizes-in-fedora-on-the-internet-hold-onto-your-hats/

# For Samsung Ultrabook with Logitech MK700: 
# xinput set-prop 'Logitech M705' 'Evdev Scrolling Distance' 4, 4, 4

# Small things:
# Tweak Tool: 
# - Windows: window action key: alt
# - Typing: ctrl key position: caps lock as ctrl, kill seq : ctrl alt backspace
#
# Settings: Keyboard: shortcuts: custom: ctrl alt t terminal
#
# /etc/sysctl.conf: kernel.sysrq = 1

# If on desktop for Micca speakers:
# $ git clone https://github.com/bmc0/dsp.git
# $ cd dsp
# $ ./configure --disable-dsp --disable-fftw3
# $ make
# $ sudo make install
# cp in ladspa_dsp into ~/.config
# cp ~/.config/pulse/default.pa in place to load the ladspa_dsp module

# # If using wireless adapter:
# git clone https://github.com/abperiasamy/rtl8812AU_8821AU_linux.git
# cd rt18812AU_8821AU_linux
# sudo make -f Makefile.dkms install
